#! /usr/bin/env zsh

# Copyright (c) 2022 Remo Ronca 106963724+sobchak-security@users.noreply.github.com
# MIT License

# NOTE print help with perldoc core/f_gpg_export_pubkey

# $1  - user or email address
# [$2]  - keyring
# [$3]  - trustdb
function f_gpg_export_pubkey() {
    local __keyring=${2:-$(gpgconf --list-dirs homedir)/pubring.kbx}
    local __trustdb=${3:-$(gpgconf --list-dirs homedir)/trustdb.gpg}

    gpg --quiet --no-tty --no-verbose --no-greeting --no-default-keyring \
        --with-colons --no-auto-check-trustdb --always-trust \
        --trustdb-name ${__trustdb} --keyring ${__keyring} \
        --export --armor ${1}
}

[[ -z ${(%):-%x} ]] && f_gpg_export_pubkey ${@}

: <<END_OF_DOCS

Exports a public key from a GPG keyring.

=head1 NAME

f_gpg_export_pubkey--Exports a public GPG key.

=head1 SYNOPSIS

f_gpg_export_pubkey name [keyring] [trustdb]

=head1 ARGUMENTS

=over

=item name

The user name or email address to search for.

=item keyring

The keyring to search for name (default: ${GNUPGHOME}/pubring.kbx).

NOTE if keyring is passed as an argument, the default keyring is not searched 
for name.

=item trustdb

The trust database to use for this operation (default: ${GNUPGHOME}/trustdb.gpg)

=back

=head1 DESCRIPTION

Looks up name in keyring and writes its public key to STDOUT. 

=head1 EXAMPLES

source gpg/f_gpg_export_pubkey ; f_gpg_export_pubkey user@domain.com /path/to/pubring.kbx

=head1 AUTHOR

L<Remo Ronca|mailto:106963724+sobchak-security@users.noreply.github.com>

=head1 LICENSE AND COPYRIGHT

MIT License

=cut

END_OF_DOCS
